/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularis;

import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import model.Examen;
import controller.Controller;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Alumne;
import model.Notas;

/**
 *
 * @author informaticos
 */
public class Vista extends javax.swing.JFrame {
    private static Examen exam;
    private static Alumne alumne;
    private static final ArrayList<PanelPregunta> paneles = new ArrayList<PanelPregunta>();
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }   
    
    public void setExamen (Examen exam){
        this.exam = exam;
        pintarExamen();
    }
    
    private boolean checkRadios(){
        Iterator<PanelPregunta> it = paneles.iterator();
        int mal=0;
        while(it.hasNext()){
            PanelPregunta panel = it.next();
            if(!panel.getR1().isSelected() && !panel.getR2().isSelected() && !panel.getR3().isSelected() && !panel.getR4().isSelected()){
                mal++;
            }
        }
        if(mal!=0){
            return false;
        }
        return true;
    }
    
    private void pintarExamen(){
        int numPreguntas = exam.getPreguntes().size();
        PanelPregunta panelpregunta = null;
        System.out.print(numPreguntas);
        
        
        for(int i=1;i<=numPreguntas;i++){
            panelpregunta = new PanelPregunta(exam.getPreguntes().get(i-1));
            panelpregunta.setLabelpregunta("Pregunta: " + i);
            panelpregunta.setBounds(10, (200*i)-200 ,610, 200);
            panelpregunta.setVisible(true);
            jPanel1.add(panelpregunta);
            paneles.add(panelpregunta);
            }
            JButton botoFinalitzar = new JButton();
            botoFinalitzar.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if(checkRadios()){
                    if(JOptionPane.showConfirmDialog(null, "Estàs segur que vols finalitzar? No podràs tornar enrere.", "Atenció!", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                        System.out.println(Controller.resultatExamen());
                        Notas notas = new Notas();
                        notas.setNotaTest(Controller.resultatExamen());
                        Controller.insertarNotas(notas);
                        if(Controller.resultatExamen()<=5){
                            Redaccio redac = new Redaccio(exam);
                            redac.setTema(0);
                            redac.setLocationRelativeTo(null);
                            redac.setVisible(true);
                        }else if(Controller.resultatExamen()>5){
                            Redaccio redac = new Redaccio(exam);
                            redac.setTema(1);
                            redac.setLocationRelativeTo(null);
                            redac.setVisible(true);
                        }
                        Controller.afegirExamenAlumne(exam.getCodi());
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Atenció! T'has deixat alguna pregunta sense respondre!");
                }
                
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
            botoFinalitzar.setBounds((jPanel1.getWidth()/2)-50, (numPreguntas * panelpregunta.getHeight()), 150, 45);
            botoFinalitzar.setVisible(true);
            botoFinalitzar.setText("FINALITZAR EXAMEN");
            jPanel1.add(botoFinalitzar);
            jPanel1.setPreferredSize(new Dimension(jPanel1.getWidth(), (numPreguntas * panelpregunta.getHeight())+75));
            jPanel1.revalidate();
            jPanel1.repaint();
            pack();
    }
    
    public ArrayList<PanelPregunta> getPanels(){
        return paneles;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 0));
        jPanel1.setLayout(null);
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
